### PR TITLE
net-p2p/monero: Bumped to 0.17.8 and added live ebuild

### PR DESCRIPTION
**Pull request by billyb2**
Since this repository is unfortunately no longer actively maintained, I added both an ebuild for the (as of writing) latest version, and a live ebuild.

### CODE REVIEW

**Comment by telans** [comment]
Thanks for doing this, although I've already added most packages from here to GURU. (probably should've added a note, @00-matt could you please?)

https://github.com/gentoo/guru/tree/master/net-p2p/monero

I've also unbundled all the dependencies into their own packages

**Comment by billyb2** [comment]
@telans My bad, I apologize. Would you want me to push the live ebuild fork to your repository?

**Comment by telans** [comment]
> My bad, I apologize.

No worries, there's no harm in merging this, I just thought GURU would be a good place to put the packages now that this repository isn't maintained. GURU isn't my repository, but a collaborative repository/project maintained by gentoo users

https://github.com/gentoo/guru
https://wiki.gentoo.org/wiki/Project:GURU

There's a little bit of effort needed in order to commit to GURU (https://wiki.gentoo.org/wiki/Project:GURU/Information_for_Contributors), but if you would rather I can just commit the live ebuild myself

**Comment by billyb2** [comment]
Yea would you mind commiting the live build, that would be great!

**Comment by telans** [comment]
As I've unbundled the dependencies of the package, would it be better to still depend on the (versioned) dependencies or use git submodules & bundled dependencies? I'm leaning towards still use the unbundled dependencies and have the purely monero aspects of this package be live

**Comment by billyb2** [comment]
I agree, it would save a lot of compilation time (if the dependencies are already installed), as well as network bandwidth.

**Comment by billyb2** [comment]
I saw your ebuild in the [GURU repo](https://gitweb.gentoo.org/repo/proj/guru.git/diff/net-p2p/monero/monero-9999.ebuild?h=dev), thank you!

**Pull request closed without merging**
